import { TextField } from "@/components/Form/Field";
import { Layout } from "@/components/Layout";
import { Form, Formik } from "formik";
import Head from "next/head";
import * as Yup from "yup";
import type { GetStaticProps } from "next";
import { InnerLayout } from "@/components/InnerLayout";

export type FormikRegisterForm = {
  name: string;
  phone: string;
};

export default function Register() {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <InnerLayout>
          <div
            className={`flex w-full flex-grow flex-col items-center justify-center`}
          >
            {/* <h1 className="font-montserrat text-[1.75rem] font-bold text-primary">
              Registration
            </h1> */}
            <Formik<FormikRegisterForm>
              initialValues={{ name: "", phone: "" }}
              onSubmit={async (values, action) => {
                action.setSubmitting(true);
                try {
                  const res = await fetch("/api/register", {
                    method: "POST",
                    body: JSON.stringify(values),
                  });

                  // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment
                  const response: { result: string } = await res.json();

                  console.info(response);
                  if (res.ok) {
                    alert("Registered!");
                    action.resetForm();
                  } else {
                    alert("An Error Occurred.");
                  }
                } catch (err) {
                  console.error(err);
                } finally {
                  action.setSubmitting(false);
                }
              }}
              validationSchema={Yup.object().shape({
                name: Yup.string().required("Required."),
                phone: Yup.string()
                  .required("Required.")
                  .matches(
                    /^(\+?6?01)[0|1|2|3|4|6|7|8|9]-*[0-9]{7,8}$/,
                    "Invalid format.",
                  ),
              })}
            >
              {({ isSubmitting }) => (
                <Form className="flex w-full flex-col items-center justify-center gap-2">
                  <TextField<FormikRegisterForm>
                    disabled={isSubmitting}
                    formikKey="name"
                    label="Name"
                  />
                  <TextField<FormikRegisterForm>
                    disabled={isSubmitting}
                    type="tel"
                    formikKey="phone"
                    label="Phone no."
                  />
                  <button
                    type="submit"
                    className="w-full max-w-[400px] rounded-full bg-black py-1.5 font-montserrat uppercase text-white"
                  >
                    Register
                  </button>
                </Form>
              )}
            </Formik>
          </div>
        </InnerLayout>
      </Layout>
    </>
  );
}
export const getStaticProps: GetStaticProps = async (context) => {
  return {
    props: {
      // You can get the messages from anywhere you like. The recommended
      // pattern is to put them in JSON files separated by locale and read
      // the desired one based on the `locale` received from Next.js.
      // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-unsafe-member-access
      messages: (await import(`@/locales/${context.locale}.json`)).default,
    },
  };
};
